baseURL = 'https://chernand.io'
languageCode = 'en-us'
title = 'Christian Hernandez'
theme = "sada"
publishDir = "docs"
disableKinds = ["taxonomy", "taxonomyTerm"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    name = "All About Christian Hernandez"
    title = "chernand.io"
    author = "Christian Hernandez"
    description = "Summary"
    copyright = "Copyright 2022"
    theme = "light" # `dark` or `light`
    useResources = false

    # Profile section
    [params.profile]
        name = "Christian Hernandez"
        photo = "images/profile.jpg"

    # Education section
    [params.education]
        title = "Education"

        [[params.education.list]]
        degree = "Bachelors in Information Systems"
        college = "ITT Technical Institute"
        dates = "2005 - 2009"

    # Languages section
    [params.language]
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Fluent"
				
        [[params.language.list]]
        language = "Spanish"
        level = "Intermediate"

        [[params.language.list]]
        language = "German"
        level = "Intermediate"

    # Languages section
    [params.lt]
        title = "Links"

        [[params.lt.list]]
        icon = "fab fa-linkedin-in"
        url = "https://www.linkedin.com/in/chernandez1982/"
        site = "LinkedIn"

        [[params.lt.list]]
        icon = "fab fa-github"
        url = "https://github.com/christianh814"
        site = "GitHub"
		
        [[params.lt.list]]
        icon = "fa fa-cloud"
        url = "https://bsky.app/profile/christianh814.bsky.social"
        site = "BlueSky Social"
		
        [[params.lt.list]]
        icon = "fab fa-twitter"
        url = "https://twitter.com/christianh814"
        site = "Twitter"

        [[params.lt.list]]
        icon = "fab fa-youtube"
        url = "https://www.youtube.com/playlist?list=PLvuF36Z5jU-OL0A-j_Gfdx03K2iXg_k2C"
        site = "Presentations and Keynotes"
	
        [[params.lt.list]]
        icon = "fab fa-youtube"
        url = "https://www.youtube.com/playlist?list=PLvuF36Z5jU-OHDLOT0KgN2x1s9CK8coac"
        site = "Demos and Webinars"
		
        [[params.lt.list]]
        icon = "fas fa-file-alt"
        url = "https://github.com/christianh814/vid-playlists/tree/main/blogs"
        site = "Blogs"
		
        [[params.lt.list]]
        icon = "fa fa-book"
        url = "https://www.oreilly.com/library/view/argo-cd-up/9781098141998/"
        site = "Books"
	

    # Interests section
    [params.hobbies]
        title = "Certifications"

        [[params.hobbies.list]]
        interest = "[NVIDIA Certified Professional: AI Operations](https://www.credly.com/badges/0acc664b-27b6-4267-a278-0e8db949a7ba/public_url)"

        [[params.hobbies.list]]
        interest = "[NVIDIA Certified Associate: AI Infrastructure and Operations](https://www.credly.com/badges/f319d5d0-37e0-41ca-9033-e539dcd23b5d/public_url)"

        [[params.hobbies.list]]
        interest = "[Red Hat Certified Specialist](https://rhtapps.redhat.com/verify/?certId=110-326-071)"

        [[params.hobbies.list]]
        interest = "[Certified Kubernetes Administrator](https://www.credly.com/badges/deb85a40-1236-417c-82e5-8dff428771e8/public_url)"

	[[params.hobbies.list]]
        interest = "[GitOps at Scale Certified for Argo](https://www.credly.com/badges/7503b054-e1f2-4a91-b2ba-0fcbe6f0b652/public_url)"

	[[params.hobbies.list]]
        interest = "[GitOps Fundamentals Certified for Argo](https://www.credly.com/badges/f19bb016-4d82-47ba-ae22-d230b97a00f6/public_url)"

	[[params.hobbies.list]]
        interest = "[Introduction to Continuous Delivery and GitOps using Argo CD](https://www.credential.net/542a9965-1799-4f49-9f42-e9b0f37b8ecf)"

        [[params.hobbies.list]]
        interest = "[Cisco CCNA](https://www.credly.com/badges/1790a432-6dd2-4905-ac2a-44a9d6b1aad1/public_url)"

        [[params.hobbies.list]]
        interest = "CompTIA: A+, Network+, Linux+"

    [params.aboutme]
        description = "Technologist with experience in enterprise architecture, DevOps, tech support, advocacy, software engineering, and management. Passionate about OpenSource and Cloud-Native Architecture. I am an OpenGitOps Maintainer and an Argo Project Marketing SIG memeber. Lately I've been focusing on Kubernetes, DevOps, and GitOps practices."

    # Experiences section
    [params.experiences]
        title = "Experiences"
        resumelink = "https://www.linkedin.com/in/chernandez1982/"

        [[params.jobs.list]]
        position = "Technical Marketing Engineer and Tech Lead"
        dates = "October 2025 - *Present*"
	link = "https://www.cisco.com/"
        company = "Cisco"
        details = "Technical Marketing Engineer on Cisco's Isovalent team, driving cloud-native networking and security adoption through hands-on content and demos with Cilium and Tetragon. Create blogs, labs, videos, and guides that educate DevOps, NetOps, and SecOps practitioners while enabling partners and customers. Collaborate closely with product and engineering teams to research real-world use cases, drive go to market strategy, and help shape product updates. Deliver workshops, webinars, and conference sessions that translate complex technical capabilities into practical guidance that informs both technical and business decisions."

        [[params.jobs.list]]
        position = "Head of Community Engineering"
        dates = "June 2023 - July 2025"
	link = "https://akuity.io"
        company = "Akuity"
        details = "Responsible for developing and executing Akuity's OpenSource strategy. Lead a team of DevRel, Community specialists and OpenSource Engineers to promote Akuity's platform and OpenSource contributions. Communicate Akuity's unique and innovative worldview and approach to the world of engineers and engage with users to solve complex problems and create scale by sharing these solutions with software engineers and platform engineers globally. In addition to engaging deeply with the community, I also work closely with Akuity’s product and engineering teams to ensure that the needs of the community are always served by Akuity's Enterprise for Argo platform."

        [[params.jobs.list]]
        position = "Senior Principal Product Manager"
        dates = "October 2022 - June 2023"
	link = "https://www.redhat.com/"
        company = "Red Hat"
        details = "Senior Principal Technical Product Manager in the Cloud Services Business Unit. Focused on Red Hat's Secure Supply Chain products including Red Hat Trusted Content and Red Hat Trused Application Pipeline."

        [[params.jobs.list]]
        position = "Head of Developer Experience and Community Management"
        dates = "June 2022 - October 2022"
	link = "https://codefresh.io/"
        company = "Codefresh"
        details = "Spearhead open-source innovation and collaboration initiatives, delivering valuable contributions to the Argo Project, OpenGitOps, and build/cultivate Codefresh’s developer enablement programs. Help build, guide, and strengthen Codefresh’s open-source commitments and developer engagement by solidifying Codefresh's open-source footprint in those respective communities."

        [[params.jobs.list]]
        position = "Senior Principal Technical Marketing Manager"
        dates = "September 2014 - June 2022"
	link = "https://www.redhat.com/"
        company = "Red Hat"
        details = "As a Technical Marketing Manager for Red Hat's OpenShift Kubernetes Platform, I am responsible for technically related internal and external facing tools and collateral that will help Red Hat accelerate adoption of its cloud-native strategies. I work with Product Management and Product Marketing to develop our go to market strategy for OpenShift GitOps (Red Hat's Argo CD offering), evangelize OpenShift and OpenShift GitOps by the way of blogs, videos, workshops, and streams."
        otherstuff = "_Other Positions Held: Principal Technical Marketing Manager, Senior Specialist Solution Architect, Associate Specialist Solution Architect_"

        [[params.jobs.list]]
        position = "Senior Infrastructure Engineer and Team Lead"
        dates = "April 2007 - August 2014"
	link = "https://4over.com/"
        company = "4over"
        details = "Responsible for designing, implementation, and support for 4over's IT infrastructure. Evaluate system tools, upgrades, and hardware to support the expanding needs of the company. Provide a scalable, robust, and secure solutions that meets 4over's goals. Work with developers to provide an environment for rapid development of internal and external applications. As a team lead, responsible for other Infrastructure Engineers and their tasks."
        otherstuff = "_Other Positions Held: Infrastructure Engineer, Associate System Administrator_"

    # Projects section
    [params.projects]
        title = "Open Source"

        [[params.projects.list]]
        title = "OpenGitOps - Maintainer"
        url = "https://opengitops.dev/"
        description = "The OpenGitOps Working Group is a CNCF initiative to establish and promote standards around GitOps. As a member of the events committee, I help organize GitOpsCon. I also help with the social media promotion. As a maintainer, I help review and merge pull requests and updates. "
		
	[[params.projects.list]]
        title = "ArgoProj Marketing Committee Member"
        url = "https://argoproj.github.io/"
        description = "The Argo Project is the umbrella project where all Argo related technologies are governed. This includes technologies such as Argo CD, Argo Workflows, Argo Rollouts, and Argo Events. As a member of the marketing committee, I help with marketing related materials and events such as ArgoCon. I also help with the social media promotion."
		
	[[params.projects.list]]
        title = "CD Foundation Ambassador"
        url = "https://cd.foundation/ambassadors/"
        description = "Support CDF Community with surveys, as well as collaborative and individual blogs. Contribute to upskilling, building competencies through podcast, webinars, reviewing books and industry reports on State of Continuous Delivery. Represent the CDF Community publicly at events like cdCon, other member events, and local community events hosted by the ambassadors themselves. Support with training & certification initiatives by ambassadors with experience with member projects & products."

    # Skills section
    [params.skills]
        title = "Skills"

        [[params.skills.list]]
        skill = "**Enterprise Architecture**"
        skillrating = "System Adminsitration, Network Administration, Storage, Databases, Load Balancing, and Disaster Recovery" # out of 100
                
        [[params.skills.list]]
        skill = "**Programming/Development**"
        skillrating = "Golang, NodeJS, Javascript, PHP, and advanced Shell Scripting"
		
        [[params.skills.list]]
        skill = "**DevOps**"
        skillrating = "AWS and Azure cloud, automation with Ansible and Chef, Kubernetes, Helm, Argo CD, advanced CI/CD practices with GitOps"
